CREATE TABLE IF NOT EXISTS folders (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    user_id INT UNSIGNED DEFAULT NULL,
    title VARCHAR(255) NOT NULL,
    create_at DATETIME DEFAULT NOW(),
    update_at DATETIME DEFAULT NOW(),

    FOREIGN KEY (user_id) REFERENCES users(id)
);
