version: "3.8"

volumes:
  mysql_db_volume:
    driver: local

networks:
    php_kek:
      driver: bridge
services:
  adminer:
    image: adminer
  app:
    build:
      context: docker/php
    restart: always
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html/
    networks:
      - php_kek
  mysql_db:
    image: "mysql:8"
    restart: always
    ports:
      - "33062:3306"
    environment:
      MYSQL_ROOT_PASSWORD: KJKszpj
    volumes:
      - "mysql_db_volume:/var/lib/mysql"
    networks:
      - php_kek
